title = "Martin Justin"
Description = "Martin Justin's portfolio website."
baseURL = "https://martin-justin.github.io"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id
enableRobotsTXT = true

[params]
  author = "Martin Justin"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "favicon.svg"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Martin Justin"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:martin1123581321@gmail.com"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
